### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by amirmojiry** [boukeversteegh/pptpd-monitor#12]
When I tried to install this script, I got this error

> pptpd-monitor.py:69: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if interval is 0:
> Traceback (most recent call last):
>   File "pptpd-monitor.py", line 288, in <module>
>     logfile = args.file.file
> AttributeError: '_io.TextIOWrapper' object has no attribute 'file'

Thanks for your help

**Comment by boukeversteegh** [comment]
With which python version are you running this?

The code was upgraded from 2to3 at the end of 2018, the latest version at that time was 3.7. Perhaps try with 3.7 or 3.6?

**Comment by boukeversteegh** [comment]
I see a fork at https://github.com/Rolloniel/pptpd-monitor/commit/0d1c1d48b49b2008e16ef4a9bbca45b0753f1162 by @Rolloniel

Unfortunately no pull request was made. You could try that branch. Let me know if it worked, then I'll merge that fix into here.

**Comment by Rolloniel** [comment]
That was Python 3.6 specific fix, TextIOWrapper object changed the naming convention a bit. Also, make sure not to merge other commits, they were CentOS specific because they use a slightly different logging format

**Comment by boukeversteegh** [comment]
> That was Python 3.6 specific fix, TextIOWrapper object changed the naming convention a bit. Also, make sure not to merge other commits, they were CentOS specific because they use a slightly different logging format

Thanks for your reply! I'll only merge that first commit, if @amirmojiry can confirm that it works in python 3.7 as well. I don't mind to raise the requirements to 3.6 or higher

**Comment by amirmojiry** [comment]
> I see a fork at [Rolloniel@0d1c1d4](https://github.com/Rolloniel/pptpd-monitor/commit/0d1c1d48b49b2008e16ef4a9bbca45b0753f1162) by @Rolloniel that may fix this issue.
> 
> Unfortunately no pull request was made. You could try that branch. Let me know if it worked, then I'll merge that fix into here.

Thanks @boukeversteegh 
I test with [This File](https://raw.githubusercontent.com/Rolloniel/pptpd-monitor/4121a901294027bdff260c33b3e4f762a2d9aff6/src/pptpd-monitor.py) ([Rolloniel@0d1c1d4](https://github.com/Rolloniel/pptpd-monitor/commit/0d1c1d48b49b2008e16ef4a9bbca45b0753f1162) fork) and it works!

**Comment by boukeversteegh** [comment]
Glad it worked for you @amirmojiry . And which python version are you on, please?

**Comment by amirmojiry** [comment]
3.8.5

**Comment by boukeversteegh** [comment]
I've merged https://github.com/boukeversteegh/pptpd-monitor/commit/0d1c1d48b49b2008e16ef4a9bbca45b0753f1162 and updated the required python versions :-)

Thank you @amirmojiry and @Rolloniel
